# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

container: ubuntu:16.04

steps:
- script: 'apt-get install qt5-default'
  displayName: 'Install Qt5'

- script: 'cd build && cmake ..'
  displayName: 'Configure git-of-life'

- script: 'make'
  displayName: 'Build git-of-life'